name: Build

on:
  push:
    paths: ['lcd_test/main.c']
  pull_request:
    paths: ['lcd_test/main.c']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Build with sdcc
      uses: docker://panoti/sdcc
      with:
        args: cd lcd_test && sdcc -mmcs51 main.c

    - name: Convert to binary
      working-directory: lcd_test
      run: objcopy -Iihex -Obinary main.ihx service_tastatur_v3.3.u3

    - name: Upload ROM artifact
      uses: actions/upload-artifact@v6
      with:
        name: servicet
        path: lcd_test/service_tastatur_v3.3.u3
