name: Build

on:
  push:
    paths: ['firmware/main.c']
  pull_request:
    paths: ['firmware/main.c']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Install sdcc
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: sdcc binutils

    - name: Build with sdcc
      working-directory: firmware
      run: sdcc -mmcs51 main.c

    - name: Convert to binary
      working-directory: firmware
      run: objcopy -Iihex -Obinary main.ihx service_tastatur_v3.3.u3

    - name: Upload ROM artifact
      uses: actions/upload-artifact@v6
      with:
        name: servicet
        path: firmware/service_tastatur_v3.3.u3
